apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    purpose: poc
    environment: Dev
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx